name: hydrify
description: "A new Flutter project."

publish_to: 'none' 
version: 0.0.1+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  provider: ^6.1.2
  syncfusion_flutter_charts: ^28.2.4+1
  flutter_blue_plus: ^1.35.2
  sqflite: ^2.4.1
  permission_handler: ^11.3.1
  intl: ^0.20.2
  geolocator: ^13.0.2
  firebase_auth: ^5.5.0
  syncfusion_flutter_gauges: ^28.2.6
  pinput: ^5.0.1
  cloud_functions: ^5.5.1
  path_provider: ^2.0.15
  shared_preferences: ^2.5.2
  local_auth: ^2.3.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  encrypt: ^5.0.3
  equatable: ^2.0.7
  gradient_borders: ^1.0.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_inner_shadow: ^0.0.1
  fl_chart: ^0.70.1
  glassmorphism: ^3.0.0
  wave: ^0.2.2
  flutter_local_notifications: ^19.4.1
  fluttertoast: ^9.0.0
  image_picker: ^1.0.1
  url_launcher: ^6.3.2
  share_plus: ^7.2.1 
  screenshot: ^3.0.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/weather/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno-VariableFont_wght.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  